Repository OpenHistoricalMap/ohm-website, pull requests merged in 2025-03, with the labels that each got.

#275 202503 twn repairs
  config/locales/ce.yml
  config/locales/de.yml
  config/locales/fr.yml
  config/locales/ko.yml
  config/locales/lb.yml
  config/locales/nl.yml
  config/locales/pa.yml
  config/locales/ro.yml
  config/locales/ru.yml
  config/locales/sco.yml
  config/locales/sl.yml
  config/locales/sr.yml
  config/locales/th.yml
Labels: inappropriate-translations

#274 Localisation updates from https://translatewiki.net.
  config/locales/bg.yml
  config/locales/ce.yml
  config/locales/da.yml
  config/locales/de.yml
  config/locales/en-GB.yml
  config/locales/es.yml
  config/locales/eu.yml
  config/locales/fr.yml
  config/locales/fy.yml
  config/locales/he.yml
  config/locales/is.yml
  config/locales/ko.yml
  config/locales/lb.yml
  config/locales/mk.yml
  config/locales/nl.yml
  config/locales/pa.yml
  config/locales/pt-BR.yml
  config/locales/pt-PT.yml
  config/locales/ro.yml
  config/locales/ru.yml
  config/locales/sco.yml
  config/locales/sl.yml
  config/locales/sr.yml
  config/locales/th.yml
  config/locales/tr.yml
  config/locales/vi.yml
  config/locales/zh-CN.yml
  config/locales/zh-TW.yml
Labels: inappropriate-translations

#269 Re: https://github.com/OpenHistoricalMap/issues/issues/929, changes t…o ohm-website to allow it to work with map-styles as an npm module.
  app/assets/javascripts/application.js
  app/assets/javascripts/index.js
  app/assets/javascripts/leaflet.map.js
  app/assets/javascripts/ohm.style.japanese.js
  app/assets/javascripts/ohm.style.js.erb
  app/assets/javascripts/ohm.style.original.js
  app/assets/javascripts/ohm.style.railway.js
  app/assets/javascripts/ohm.style.woodblock.js
  config/initializers/assets.rb
  package.json
  yarn.lock
Labels: javascript, big-pr, merge-commits

#279 Rewrite About page
  app/views/site/about.html.erb
  config/locales/en.yml
Labels: content
